### PR TITLE
Basic and X509 Auth, Proxy fixes and Puppeteer support for client side generated content

### PR DESCRIPTION
**Pull request by konstantinblaesi**
- *Did you make sure the commit messages are clear, and WIP commits have been squashed?*
- *Did you lint and test the code (`npm test`)?*  Passes for Node.js >= v6.4.0
- *Did you include tests for your code?* No
- *If applicable, did you update the documentation with the changes you made?* No
- *If you made changes to the docs, did you run a quick spell check?* No

## What this PR changes
* optionally use puppeteer for fetch queueItems. This enables crawling of client side generated content (e.g. ajax) and is one solution to #386 . The feature can be enabled by setting `crawler.clientSideGeneratedContent =  true;`
* always sets `Connection: keep-alive`, because we've encountered slow (application) webservers closing connections before the response was fully sent/received. Chrome seems to do the same.
* Implements http basic and x.509 certificate authentication for individual hosts instead
* refactors the proxy crawler implementation, because according it needs to be handled differently depending on the protocol of the queueItem or the proxy. For now I've used https://www.npmjs.com/package/tunnel which supports all combinations and http basic auth. I've only implemented http over httpand https over http in the crawler for now.

## Rationale
* the integration of puppeteer is one way of solving #386 
* the new proxy implementation might also solve #336 . Needs verification.

* as mentioned in #361 we should probably  add some docs about supported proxy configurations

As you can see in https://github.com/konstantinblaesi/node-simplecrawler/blob/c44f0b4ec18e3d7fc653eb114fa150996b9a2dd2/lib/fetch-client-puppeteer.js#L242 there are some ugly hacks to make the current crawler work with the request/response objects returned by puppeteer, because the current crawler has no generic abstractions for these and simply exposes them in different ways.

Puppeteer requires Node.js  >= v6.4.0 or better >= v7.6.0 .
I'd like to do more refactoring/cleanup making use of async/await including adding missing abstractions. Async/await requires Node.js 8.x (becoming LTS in october) unless you do transpiling one way or another.
What do you think about merging some or all of these commits?
What do you think about raising the Node.js version to >= v7.6 (async/await support) ?

### CODE REVIEW

**Comment by konstantinblaesi** [comment]
Tests on Node.js  < v6.4.0 will fail because puppeteer does not support it.
Would you consider merging the puppeteer code maybe with an experimental notice?

**Comment by fredrikekelund** [comment]
Thanks so much for your contribution, @konstantinblaesi! I am quite swamped at the moment, so I won't be able to look more closely at this for the next couple of days. Looking forward to doing so, however!

I also believe this warrants a discussion about the next generation of simplecrawler architecture. I think it's clear that using puppeteer is something we want to do, so discussing a future architecture to support that would be good.

**Comment by konstantinblaesi** [comment]
Enabling the puppeteer feature is a as simple as setting `crawler.clientSideGeneratedContent = true;`, but the feature should be considered experimental because it does not support all of simplecrawlers features/behaviour, yet. What should work is using basic auth, proxies, feching of page's content. All implementation details regarding puppeteer are in `lib/fetch-client-puppeteer.js`.

**Comment by fredrikekelund** [comment]
Just letting you know that I haven't forgotten about this, @konstantinblaesi! Excited to discuss these updates. I hope to pen a longer reply tomorrow so we can get a discussion going!

**Comment by LeMoussel** [comment]
@konstantinblaesi In `crawler.start()`, would not it be better to set `fetchClientPuppeteer` when `crawler.clientSideGeneratedContent = true`  like this 
```
Crawler.prototype.start = function() {
    var crawler = this;

    if (crawler.running) {
        return crawler;
    }

    if (crawler.clientSideGeneratedContent) {
        crawler.fetchClientPuppeteer = new FetchClientPuppeteer(crawler);
    }
```

**Comment by fredrikekelund** [comment]
Finally getting around to this now! 🥇 Lots of good stuff in here, but I think we're going to want to integrate these updates piece by piece.

The updated way of handling **proxies** is great - I haven't actually dealt with the proxy configuration for simplecrawler very much, but this seems like a much more solid way. From what I can tell, it seems to be fully backwards compatible as well, which is good.

The **authentication** logic is great too - I think it makes a lot of sense to let people specify different authentication credentials for different domains, and supporting X509 seems smart.

The change to include the **`Connection: keep-alive`** header also seems good - we should align with what browsers are doing.

I'm also very intrigued by the **puppeteer** implementation, but this brings me to maybe the most important point to discuss. I've been drafting some bigger API updates that should probably become simplecrawler 2.0. Supporting puppeteer would probably be the biggest feature for that version, and this update looks like a really solid base for that. However, seeing as puppeteer requires us to drop support for node 6.x, I would like to see if we can take some more time to get a solid API design with logical separation of concerns before we merge this. I would also prefer if we released puppeteer support through a separate npm module, so that we wouldn't always have a dependency on it.

So, here's my suggestion for how we move ahead: limit the scope of this PR to just the updated proxy logic, the new auth logic and the `Connection: keep-alive` header. Also make sure that all of those changes are supported all the way down to node 4.

We then start work on a development branch in this repository that will become simplecrawler 2. We'll probably have to find a way to discuss API decisions in an issue. I'll see if I can write down my ideas so far.

What do you think about that? I'm really intrigued by all of this, thank you for pushing simplecrawler forward!

**Comment by gombosg** [comment]
Wow, Puppeteer support would be so great! I'm using it myself as an extension, too - after fetching the headers, I'm calling Puppeteer  manually.

**Comment by robinparisi** [comment]
@konstantinblaesi Awesome work, this PR seems very promising! Any thoughts about @fredrikekelund suggestion?

**Pull request closed without merging**
