### PR TITLE
Make tests to run independently

### PR DESCRIPTION
**Pull request by kbychkov**
## What this PR changes
Currently the tests can't be run independently because they rely on the local server which started in one of the files. That is uncomfortable when working with a particular file. This commit adds the server to every file where necessary.

Also, fixed typo in `.editorconfig` and added WebStorm IDE's project folder to `.gitignore`.

### CODE REVIEW

**Comment by kbychkov** [comment]
Hello guys! Please review this PR, I think AppVeyor doesn't pass check because of misconfiguration since the repo was moved from [cgiffard/node-simplecrawler](https://ci.appveyor.com/project/cgiffard/node-simplecrawler).

**Comment by fredrikekelund** [comment]
Thanks for the PR @kbychkov! I think we would also have to destroy the server after the tests in each file have been completed – my suspision otherwise is that we continue to send requests to a server that was instantiated in a previous file.

**Comment by kbychkov** [comment]
That was in fact my first idea to wrap the server into `before` and `after` hooks. Though it will need more code changes and I'm hesitate to make the larger PR for the first time :)
I could rewrite accordingly, if it helps.

**Comment by fredrikekelund** [comment]
Hi @kbychkov! Sorry about my very slow response here – I've gone ahead and merged this.

I'm the 2nd generation maintainer for this project, but I no longer use it professionally, which is why I have very little time to devote to maintaining it. I'm impressed with the fact that you have written a MongoDB queue implementation, since it has been a long standing ambition to support distributed crawlers in that manner. If you are interested in maintaining simplecrawler, just shoot me an email (my email address is listed on my GitHub profile) and we can discuss it!

**Comment by kbychkov** [comment]
Hello @fredrikekelund! Did you received my email?

**Pull request merged**
